language: scala

jdk:
- openjdk8

matrix:
  include:
    - scala: 2.12.8
      env:
        - SBT_VERSION=1.2.8
    - scala: 2.10.7
      env:
        - SBT_VERSION=0.13.18

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_6e108da8c84d_key -iv $encrypted_6e108da8c84d_iv -in secring.gpg.enc -out secring.gpg -d;
  fi
- export PATH=${PATH}:./vendor/bundle

script:
- sbt ^^$SBT_VERSION orgScriptCI

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if grep -q "SNAPSHOT" version.sbt; then
      sbt ^^$SBT_VERSION publish;
    else
      if [ "$SBT_VERSION" = "1.2.8" ]; then
        sbt ^^$SBT_VERSION orgUpdateDocFiles;
        git reset --hard HEAD;
        git clean -f;
        git checkout master;
        git pull origin master;
        sbt ^^$SBT_VERSION release;
      fi
    fi
  fi